name: "Artifact Handler"
description: "Downloads and processes artifacts from a specified commit"
inputs:
  main-sha:
    description: "SHA of the commit to find artifacts for"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
outputs:
  config-file:
    description: "Path to the downloaded config file"
    value: ${{ steps.find-config.outputs.config-file }}
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: ./.github/actions/setup-bun

    - name: Get run ID and artifact name
      id: resolve
      run: buninator find --sha ${{ inputs.main-sha }} --token ${{ inputs.github-token }} --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }}
      shell: bash

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ steps.resolve.outputs.run_id }}
        name: ${{ steps.resolve.outputs.artifact_name }}
        path: ./artifact
        github-token: ${{ inputs.github-token }}

    - name: Find config file
      id: find-config
      shell: bash
      run: |
        CONFIG_FILE=$(find ./artifact -name '*.json' | head -n 1)
        echo "config-file=$CONFIG_FILE" >> $GITHUB_OUTPUT
        echo "Using config file: $CONFIG_FILE"
