name: 'Setup Buninator'
description: 'Setup Buninator with artifact download and authentication'
inputs:
  main-sha:
    description: 'SHA of the commit to find artifacts for'
    required: true
  gcp-sa-key:
    description: 'GCP Service Account Key'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
outputs:
  config-file:
    description: 'Path to the downloaded config file'
    value: ${{ steps.find-config.outputs.config-file }}
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: ./.github/actions/setup-bun

    - name: Get run ID and artifact name
      id: resolve
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          buninator find \
          --sha ${{ inputs.main-sha }} \
          --token ${{ inputs.github-token }} \
          --owner ${{ github.repository_owner }} \
          --repo ${{ github.event.repository.name }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ steps.resolve.outputs.run_id }}
        name: ${{ steps.resolve.outputs.artifact_name }}
        path: ./artifact
        github-token: ${{ inputs.github-token }}

    - name: Authenticate with Service Account
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ inputs.gcp-sa-key }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3

    - name: Find config file
      id: find-config
      shell: bash
      run: |
        CONFIG_FILE=$(find ./artifact -name '*.json' | head -n 1)
        echo "config-file=$CONFIG_FILE" >> $GITHUB_OUTPUT
        echo "Using config file: $CONFIG_FILE"