name: Generate Artifact
on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  actions: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    environment: test
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Find JSON files
        id: find_json
        run: |
          echo "PR commit range:"
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.json$' || true)
          echo "Found JSON files: '$FILES'"
          echo "json_files=$FILES" >> $GITHUB_OUTPUT
          if [ -z "$FILES" ]; then
            echo "No JSON files found in the PR."
            exit 0
          fi

      - name: Upload JSON artifacts
        if: steps.find_json.outputs.json_files != ''
        uses: actions/upload-artifact@v4
        with:
          name: "artifacts-${{ github.sha }}"
          path: ${{ steps.find_json.outputs.json_files }}
          
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install && bun link
      
      - name: Generate summary
        run: buninator summary --pr "$GITHUB_EVENT_PATH" --files "${{ steps.find_json.outputs.json_files }}" --run-id "${{ github.run_id }}"

      - name: Create prod PR for ${{ steps.find_json.outputs.json_files[0] }}
        run: |
          # Check if PR already exists
          if gh pr list --base prod --head main | grep -q "Deploy to Production"; then
            echo "Production PR already exists"
            exit 0
          fi        

          gh pr create \
            --base prod \
            --head main \
            --title "🚀 Deploy to Production - ${{ github.sha }}" \
            --body "Deploying changes from PR #${{ github.event.pull_request.number }} to production" \
            --label deployment,auto-created
