name: Generate Artifact
on:
  push:
    branches: [main, master]

permissions:
  contents: read
  actions: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Find JSON files
        id: find_json
        run: |
          echo "Push commit range:"
          BASE="${{ github.event.before }}"
          HEAD="${{ github.sha }}"
          echo "Base: $BASE"
          echo "Head: $HEAD"
          FILES=$(git diff --name-only "$BASE" "$HEAD" | grep '\.json$' || true)
          echo "Found JSON files: '$FILES'"
          echo "json_files=$FILES" >> $GITHUB_OUTPUT
          if [ -z "$FILES" ]; then
            echo "No JSON files found in this push."
            exit 0
          fi

      - name: Upload JSON artifacts
        if: steps.find_json.outputs.json_files != ''
        uses: actions/upload-artifact@v4
        with:
          name: "artifacts-${{ github.sha }}"
          path: ${{ steps.find_json.outputs.json_files }}
          
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
      
      - name: Generate summary
        run: buninator summary --commit "${{ github.sha }}" --files "${{ steps.find_json.outputs.json_files }}" --run-id "${{ github.run_id }}"

      - name: Create prod PR
        run: |
          # Check if PR already exists
          if gh pr list --base prod --head main --state open | grep -q "Deploy to Production"; then
            echo "Production PR already exists"
            exit 0
          fi

          gh pr create \
            --base prod \
            --head main \
            --title "🚀 Deploy to Production - ${{ github.sha }}" \
            --body "Deploying changes from commit ${{ github.sha }} to production" \
            --label deployment,auto-created
