name: Bun Audit
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Run Audit
        run: bun audit