name: Preview deployment
on:
  pull_request:
    branches: [prod]
    types: [opened, synchronize, closed]

permissions:
  contents: read
  actions: read
  pull-requests: write

env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Artifact Handler
        uses: ./.github/actions/handle-artifact
        id: resolve
        with:
          main-sha: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Service Account
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Check account access
        run: buninator check-access

      - name: Preview Changes
        run: buninator preview "${{ steps.resolve.outputs.config-file }}"
